### ISSUE TITLE
'sequences' in continuous coalescent shiny app

### ISSUE THREAD

**Issue by jpwares** [silastittes/shiny_popgen#3]
am I correct - it seems that the number of mutations mapped onto the tree in the continuous coalescent app does not always match how it is distributed across the 'sequences' in plot below - seems sometimes an extra row (mis-counting the number of mutations signaled) gets added. double-checking because have been using for grad teaching. Example attached that I struggle to explain to my students based on n or number of mutations. Sorry if I'm off. 
![Screen Shot 2023-02-02 at 1 44 47 PM](https://user-images.githubusercontent.com/9868830/216420557-34b915ff-192f-4073-90f0-84bbf5bf1bbe.png)

**Comment by silastittes** [comment]
Interesting! I definitely agree the alignment doesn’t match mutations on the tree. I can make similar things happen on my end too. Weird that’s it’s rare. Must be some bad conditional somewhere or something.
Well I welcome the excuse to refactor the code for this app and try to figure out what’s going wrong.
Sorry about that! Guess just let folks know there a bug. Will let you know if and when it’s fixed.




From: John Wares ***@***.***>
Date: Thursday, February 2, 2023 at 11:46 AM
To: silastittes/shiny_popgen ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [silastittes/shiny_popgen] 'sequences' in continuous coalescent shiny app (Issue #3)

am I correct - it seems that the number of mutations mapped onto the tree in the continuous coalescent app does not always match how it is distributed across the 'sequences' in plot below - seems sometimes an extra row (mis-counting the number of mutations signaled) gets added. double-checking because have been using for grad teaching. Example attached that I struggle to explain to my students based on n or number of mutations. Sorry if I'm off.
[Screen Shot 2023-02-02 at 1 44 47 PM]<https://user-images.githubusercontent.com/9868830/216420557-34b915ff-192f-4073-90f0-84bbf5bf1bbe.png>

**Comment by silastittes** [comment]
Ok I think I have a fix. There were several issues. 

I made some tweaks to the sequence visualization while I was at it. 

They look nice ...
![image](https://user-images.githubusercontent.com/5741919/216652687-874aef27-5ef6-401d-a6c7-f48442b99b7c.png)

But kinda cluttered when there's a lot of mutations ...
![image](https://user-images.githubusercontent.com/5741919/216653278-767a96e5-ff6b-42f1-8aba-6fd23c424d14.png)

Do you like the new or old viz more?

Will wait for feedback before merging the updates. Thanks!

**Comment by silastittes** [comment]
Oh wait, it's still wrong. lol. Still feel free to comment on alignment viz.

**Comment by jpwares** [comment]
Yeah I still see it not quite tracking correctly. Thanks so much for working on this.

Dr. John Wares
Professor – Dept of Genetics/
Odum School of Ecology
Curator – Genomics and Aquatic Invertebrate Diversity, Georgia Museum of Natural History
University of Georgia

He/Him

twitter @wareslab

If I say no to your request, it is because I recognize my current commitments and wish to honor them.






On Feb 3, 2023, at 11:23 AM, Silas Tittes ***@***.***> wrote:

[EXTERNAL SENDER - PROCEED CAUTIOUSLY]



Oh wait, it's still wrong. lol. Still feel free to comment on alignment viz.
